### ISSUE TITLE
NPM package isn't compiled to JavaScript

### ISSUE THREAD

**Issue by msiebuhr** [plainlystated/coffeescript-rrd#1]
After `npm install rrd` and opening a node shell:

```
> var rrd = require('rrd').RRD;
class RRD
      ^^^
```

Alas, it seems the package is broken for most of NPM's users.

**Comment by plainlystated** [comment]
Oops..  I'll fix this :)

**Comment by plainlystated** [comment]
Fixed @ version 1.0.1
